name: ci

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Initialize job
        uses: ./.github/actions/initialize-job

      - name: Lint
        run: yarn lint

      - name: Tests
        run: yarn test

      - name: Build
        run: yarn build
