name: pr

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/labels/types.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labels/packages.yml

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize job
        uses: ./.github/actions/initialize-job

      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize job
        uses: ./.github/actions/initialize-job

      - name: Tests
        run: yarn test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Initialize job
        uses: ./.github/actions/initialize-job

      - name: Build
        run: yarn build

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Initialize job
        uses: ./.github/actions/initialize-job

      - name: Lint commit messages
        run: yarn commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
